DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS(
ID INTEGER PRIMARY KEY NOT NULL,
FIRSTNAME TEXT NOT NULL,
LASTNAME TEXT NOT NULL
);

DROP TABLE IF EXISTS QUIZZES;

CREATE TABLE QUIZZES(
ID INTEGER PRIMARY KEY NOT NULL,
SUBJECT TEXT,
QUESTION_COUNT INTEGER,
QUIZ_DATE TEXT
);

DROP TABLE IF EXISTS RESULTS;

CREATE TABLE RESULTS(
STUDENTID INTEGER NOT NULL,
QUIZID INTEGER NOT NULL,
SCORE INT
);

INSERT INTO STUDENTS (ID, FIRSTNAME, LASTNAME) values (001, "John", "Smith");

INSERT INTO QUIZZES (ID, SUBJECT, QUESTION_COUNT, QUIZ_DATE) values (001, "Python Basics", 5, "February, 5th, 2015");

INSERT INTO RESULTS (STUDENTID, QUIZID, SCORE) values (001,001,85);